version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
  app:
    build: .
    restart: always
    ports:
     - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres: